// LOCALHOST
### READ all customers
GET http://localhost:3000/customers

### READ customer by id
GET http://localhost:3000/customers/6918e0dc8b6faee1d2b68560

### CREATE customer
POST http://localhost:3000/customers HTTP/1.1
content-type: application/json

{
    "firstName": "James",
    "lastName": "Smith",
    "email": "james.smith@example.com",
    "isSubscribed": true
}

### UPDATE customer
PUT http://localhost:3000/customers/6918e0dc8b6faee1d2b68560 HTTP/1.1
content-type: application/json

{
    "firstName":"Mary",
    "lastName":"Johnson",
    "email":"mary.johnson@example.com",
    "isSubscribed": false
}

### DELETE customer
DELETE http://localhost:3000/customers/6918e0dc8b6faee1d2b68560 HTTP/1.1

### READ all products
GET http://localhost:3000/products

### READ product by id
GET http://localhost:3000/products/6918f8bc796e86ad2e85c5f8

### CREATE product
POST http://localhost:3000/products HTTP/1.1
content-type: application/json

{
    "name": "iPhone 17 Pro",
    "category": "phone",
    "price": 1099,
    "batteryLife": 33,
    "displaySize": 6.3,
    "chip": "A19 Pro chip with 6‑core GPU",
    "isInStock": true
}

### UPDATE product
PUT http://localhost:3000/products/6918f8bc796e86ad2e85c5f8 HTTP/1.1
content-type: application/json

{
    "name": "iPhone 17 Pro Max",
    "category": "phone",
    "price": "1199",
    "batteryLife": 39,
    "displaySize": 6.9,
    "chip": "A19 Pro chip with 6‑core GPU",
    "isInStock": true
}

# {
#     "name": "iPhone 16",
#     "category": "phone",
#     "price": "699",
#     "batteryLife": 22,
#     "displaySize": 6.1,
#     "chip": "A18",
#     "isInStock": true
# }

# {
#     "name": "iPhone 17",
#     "category": "phone",
#     "price": "799",
#     "batteryLife": 30,
#     "displaySize": 6.3,
#     "chip": "A19 Pro chip with 5-core GPU",
#     "isInStock": true
# }

# {
#     "name": "iPhone Air",
#     "category": "phone",
#     "price": "999",
#     "batteryLife": 27,
#     "displaySize": 6.5,
#     "chip": "A19 Pro chip with 5-core GPU",
#     "isInStock": true
# }



### DELETE product
DELETE http://localhost:3000/products/6918f905796e86ad2e85c5fd HTTP/1.1